//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;net.rptools.maptool.model.Token&gt;
        ///  &lt;id&gt;
        ///    &lt;baGUID&gt;wKgBZTZew/dDAwAAwIAAJA==&lt;/baGUID&gt;
        ///  &lt;/id&gt;
        ///  &lt;beingImpersonated&gt;false&lt;/beingImpersonated&gt;
        ///  &lt;imageAssetMap&gt;
        ///    &lt;entry&gt;
        ///      &lt;null/&gt;
        ///      &lt;net.rptools.lib.MD5Key&gt;
        ///        &lt;id&gt;###IMAGE_MD5_SUM###&lt;/id&gt;
        ///      &lt;/net.rptools.lib.MD5Key&gt;
        ///    &lt;/entry&gt;
        ///  &lt;/imageAssetMap&gt;
        ///  &lt;x&gt;400&lt;/x&gt;
        ///  &lt;y&gt;200&lt;/y&gt;
        ///  &lt;z&gt;2&lt;/z&gt;
        ///  &lt;anchorX&gt;0&lt;/anchorX&gt;
        ///  &lt;anchorY&gt;0&lt;/anchorY&gt;
        ///  &lt;sizeScale&gt;1.0&lt;/sizeScale&gt;
        ///  &lt;lastX&gt;0&lt;/lastX&gt;
        ///  &lt;lastY&gt;0&lt;/lastY&gt;
        ///  &lt;snapToScale&gt;true&lt;/snapToScale&gt;
        ///  &lt;width&gt;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentTemplate {
            get {
                return ResourceManager.GetString("ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;entry&gt;
        ///  &lt;int&gt;###ENTRY_NUMBER###&lt;/int&gt;
        ///  &lt;net.rptools.maptool.model.MacroButtonProperties&gt;
        ///    &lt;saveLocation&gt;Token&lt;/saveLocation&gt;
        ///    &lt;index&gt;###ENTRY_NUMBER###&lt;/index&gt;
        ///    &lt;colorKey&gt;###BUTTON_COLOR###&lt;/colorKey&gt;
        ///    &lt;hotKey&gt;None&lt;/hotKey&gt;
        ///    &lt;command&gt;
        ///    ###MACRO_COMMAND###
        ///    &lt;/command&gt;
        ///    &lt;label&gt;###MACRO_NAME###&lt;/label&gt;
        ///    &lt;group&gt;###MACRO_GROUP###&lt;/group&gt;
        ///    &lt;sortby&gt;###SORTBY###&lt;/sortby&gt;
        ///    &lt;autoExecute&gt;true&lt;/autoExecute&gt;
        ///    &lt;includeLabel&gt;false&lt;/includeLabel&gt;
        ///    &lt;applyToTokens&gt;fals [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MacroTemplate {
            get {
                return ResourceManager.GetString("MacroTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;entry&gt;
        ///  &lt;string&gt;###PROP_NAME###&lt;/string&gt;
        ///  &lt;net.rptools.CaseInsensitiveHashMap_-KeyValue&gt;
        ///    &lt;key&gt;###PROP_KEY###&lt;/key&gt;
        ///    &lt;value class=&quot;string&quot;&gt;###PROP_VALUE###&lt;/value&gt;
        ///    &lt;outer-class reference=&quot;../../../..&quot;/&gt;
        ///  &lt;/net.rptools.CaseInsensitiveHashMap_-KeyValue&gt;
        ///&lt;/entry&gt;
        ///.
        /// </summary>
        internal static string TokenPropertyTemplate {
            get {
                return ResourceManager.GetString("TokenPropertyTemplate", resourceCulture);
            }
        }
    }
}
